---
# argument spec file for automation_bootcamp.my_collection.hello_world

argument_specs:
  main:
    short_description: Role description.
    options:
      my_variable:
        type: str
        description: A simple string argument for demonstration.
        default: "default_value"
